version: "3.9"

services:
    web:
        build: .
        ports:
            - "8080:8080"
    postgres:
        image: "postgres:13-alpine"
        bindings:
            - port: 5432
              containerPort: 5432
        env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: boxtotable
            - name: POSTGRES_USER
              value: postgres
        volumes:
            - source: ./data/postgres
              target: /var/lib/postgresql/data
        tags:
            - database
            - minimal
