version: "3.9"

services:
#    dotnet-watch:
#        environment:
#            - DOTNET_RUNNING_IN_CONTAINER=1
#        container_name: dotnet_watch
#        image: mcr.microsoft.com/dotnet/sdk:5.0
#        ports:
#            - 8080:8080
#        volumes:
#            - ./:/app
#        working_dir: /app/src/BoxToTabletop
#        command: dotnet watch run --no-restore -- --run
        #command: dotnet watch run --no-restore
        #$command: ./build.sh watchapp
#    web:
#        build: .
#        ports:
#            - "8080:8080"
    postgres:
        image: "postgres:13-alpine"
#        bindings:
#            - port: 5432
#              containerPort: 5432
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "boxtotabletop"
            POSTGRES_USER: "postgres"
        volumes:
            #- box-to-tabletop-data:/var/lib/postgresql/data
            #- ./data/postgres:/var/lib/postgresql/data
#            #- data:/var/lib/postgresql/data
            - type: volume    
              source: db-data
              target: /var/lib/postgresql/data
#    
#volumes:
#    data:
#        name: box-to-tabletop-data

volumes:
    db-data:
