apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boxtotabletop
spec:
  # Secret names are always required.
  secretName: boxtotabletop-com-tls
  # duration: 2160h # 90d
  # renewBefore: 360h # 15d
  # subject:
  #   organizations:
  #   - boxtotabletop
  # isCA: false
  # privateKey:
  #   algorithm: RSA
  #   encoding: PKCS1
  #   size: 2048
  # usages:
  #   - server auth
  #   - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - boxtotabletop.com
  - '*.boxtotabletop.com'
  # uris:
  # - spiffe://cluster.local/ns/sandbox/sa/example
  # ipAddresses:
  # - 164.90.254.175
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-staging #ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    # kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    # group: cert-manager.io
  # secretName: btt-cert-tls
  # privateKey:
  #   rotationPolicy: Always  
