apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      - image: sjenning/kube-nginx-letsencrypt:0.8.1-1
        name: letsencrypt
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: boxtotabletop.com,api.boxtotabletop.com,adminer.boxtotabletop.com
        - name: EMAIL
          value: admin@boxtotabletop.com
        - name: SECRET
          value: letsencrypt-certs
        - name: DEPLOYMENT
          value: btt-client
      restartPolicy: Never
# note to self: this did not work due to the known ACMEv1 issue