FROM nginx

COPY nginx.config /etc/nginx/conf.d/default.conf
COPY public/index.html /usr/share/nginx/html
COPY public/*.js /usr/share/nginx/html
COPY public/*.css /usr/share/nginx/html
COPY public/*png /usr/share/nginx/html
RUN mkdir /usr/share/nginx/html/webfonts
COPY public/webfonts/ /usr/share/nginx/html/webfonts/